sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t pandzior/docker-react -f Dockerfile.dev .

script:
  - docker run pandzior/docker-react npm run test -- --coverage